modelling:
  target_clf: rings
  numeric_cols:
    - 'length'
    - 'diameter'
    - 'height'
    - 'whole weight'
    - 'shucked weight'
    - 'viscera weight'
    - 'shell weight'
  categorical_cols:
    - 'sex'