modelling:
  target_clf: "class"
  numeric_cols:
    - "deg-malig"
  categorical_cols:
    - "age"
    - "menopause"
    - "tumor-size"
    - "inv-nodes"
    - "node-caps"
    - "breast"
    - "breast-quad"
    - "irradiat"